### ISSUE TITLE
reference error to build_id_grid

### ISSUE THREAD

**Issue by BramSchnitzler** [openearth/flowmap#48]
* Flowmap generator version: 1.0.0
* Python version: 3.6
* Operating System: Windows 8.1 64-bit

### Description

Triedto generate subgridded waterdepths. Subgridding failed because function 'build_id_grid' was not found in folder 'flowmap'. 

Possible solution:
replace:
id_grid = subgrid.build_id_grid(dem)
with:
id_grid = self.build_id_grid(dem)

### What I Did

```
ugrid_dem = flowmap.formats.ugrid.UGrid(path = r'd:\Project\P940\05_Analysis\Resultaten\1131\Leerdam\leerdamwest_map.nc', dem = r'd:\Project\P940\05_Analysis\GIS\AHN\07_resultaat\C24\1131\resultaten\aw_ahn_def.tif')
ugrid_dem.subgrid(5,'waterdepth',format='.tiff')

Traceback (most recent call last):

  File "<ipython-input-29-b207b2aeb0a4>", line 2, in <module>
    ugrid_dem.subgrid(5,'waterdepth',format='.tiff')

  File "C:\Users\schnitzler\AppData\Local\Continuum\anaconda2_64\envs\P940_flowmap_05feb\lib\site-packages\flowmap\formats\ugrid.py", line 294, in subgrid
    id_grid = subgrid.build_id_grid(dem)

AttributeError: module 'flowmap.subgrid' has no attribute 'build_id_grid'
```

**Comment by SiggyF** [comment]
Fixed in #54
