### ISSUE TITLE
error in subgrid_compute

### ISSUE THREAD

**Issue by BramSchnitzler** [openearth/flowmap#50]
* Flowmap generator version: 1.0.0
* Python version: 3.6 
* Operating System: Windows 8.1 64-bit

### Description

Tried to create subgrid with work-arounds for issues #48 and #49 . Got an error on subgrid_compute in 'compute_band'.

### What I Did

```
ugrid_dem = flowmap.formats.ugrid.UGrid(path = r'd:\Project\P940\05_Analysis\Resultaten\1131\Leerdam\leerdamwest_map.nc', dem = r'd:\Project\P940\05_Analysis\GIS\AHN\07_resultaat\C24\1131\resultaten\aw_ahn_def.tif')
#ugrid_dem.subgrid(5,'waterdepth',format='.tiff')



logger = logging.getLogger(__name__)
t = 5
method = 'waterdepth'
format = '.tiff'


"""compute refined waterlevel using detailled dem, using subgrid or interpolate method"""
dem = read_dem(ugrid_dem.options['dem'])
grid = ugrid_dem.ugrid
data = ugrid_dem.waterlevel(t)
if method in ('waterdepth', 'waterlevel'):

    # this is slow
    table_name = ugrid_dem.generate_name(
        ugrid_dem.path,
        suffix='.nc',
        topic='tables'
    )
    table_path = pathlib.Path(table_name)
    if table_path.exists():
        logger.info('reading subgrid tables from %s', table_path)
        tables = subgrid.import_tables(str(table_path))
    else:
        logger.info('creating subgrid tables')
        id_grid = ugrid_dem.build_id_grid(dem)
        tables = subgrid.build_tables(grid, dem, id_grid,None)
    logger.info('computing subgrid band')
    if format == '.geojson':
        if method == 'waterdepth':
            raise ValueError('waterdepth method only has .tiff format output')
        feature_collection = subgrid.compute_features(grid, dem, tables, data, method=method)
    elif format == '.tiff':
        # this is also slow
        band = subgrid.compute_band(grid, dem, tables, data, method=method)


Traceback (most recent call last):

  File "<ipython-input-33-ac79f7003f01>", line 1, in <module>
    band = subgrid.compute_band(grid, dem, tables, data, method=method)

  File "C:\Users\schnitzler\AppData\Local\Continuum\anaconda2_64\envs\P940_flowmap_05feb\lib\site-packages\flowmap\subgrid.py", line 235, in compute_band
    result = subgrid_compute(row, dem=dem, method=method)

  File "C:\Users\schnitzler\AppData\Local\Continuum\anaconda2_64\envs\P940_flowmap_05feb\lib\site-packages\flowmap\subgrid.py", line 44, in subgrid_compute
    row['slice'][2]:row['slice'][3]

IndexError: tuple index out of range
```

**Comment by SiggyF** [comment]
Fixed in #54
